### ISSUE TITLE
Gallery plugin install crashed themes

### ISSUE THREAD

**Issue by t0dd** [bestwebsoft/gallery-wordpress-plugin#1]
I have two sites with fresh new Wordpress installs. ( Wordpress 4.1) With the Lifestyle Theme (which also has the Genesis theme as a dependency).  After installing the Gallery Plugin (version 4.2.7) all of the installed themes are broken.  Error: missing stylesheet. 
Sites: http://phillips.tamarackpm.com http://equinox.tamarackpm.com
I have 35+ sites running the same configuration with no problems including 7 new sites.  I'm hesitant to install Gallery in the remaining new sites until this gets resolved. Thanks.

**Comment by bestwebsoft** [comment]
Thank you for contacting us and thank you for drawing our attention to this issue. We have released an update today, in which this bug was fixed.
Sincerely,
The BestWebSoft Team

**Comment by t0dd** [comment]
We're good now.  Thanks!
